#name, main, version and api are required
name: NuclearEconomy
main: com.fcmcpe.nuclear.economy.NuclearEconomyPlugin
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1"
api: ["1.0.0"]

load: STARTUP
authors: ["Snake1999"]
description: "Nuclear economy plugin"
website: https://github.com/FunCraftNetwork/NuclearPlugins
