#name, main, version and api are required
name: BaiduIPGEO4Nuclear
main: com.fcmcpe.nuclear.core.BaiduIPGEOPlugin
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1"
api: ["1.0.0"]

load: STARTUP
authors: ["Snake1999"]
description: "Baidu IP-GEO Engine for Nuclear core plugin"
website: https://github.com/FunCraftNetwork/NuclearPlugins

depend: ["NuclearCore"]
