#name, main, version and api are required
name: NuclearLogin
main: com.fcmcpe.nuclear.login.NuclearLoginPlugin
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "2 build 4"
api: ["1.0.0"]

load: STARTUP
authors: ["Snake1999", "Pub4Game"]
description: "Nuclear login plugin"
website: https://i-have-no-website-yet.oops

depend: ["NuclearCore"]